Add automated e2e test flow on Cloud Build (#94)
This PR implements an automated e2e test flow that runs automatically for pull requests. The test flow does the following:
* automatically create a new managed dns zone that is specific to the test run
* run all `make` targets to set up the application
* do a basic `curl` to make sure the frontend is reachable
* run Cypress e2e tests
* upload e2e test artifacts (videos, screenshots) [to GCS](https://console.cloud.google.com/storage/browser/crfa-reference-web-app-infra-e2e-artifacts)
* tear down all resources created as part of the e2e test*


\* with the exception of NS records added to the top-level domain, which are difficult to automatically clean up

diff --git a/webui/cypress/cloudbuild.yaml b/webui/cypress/cloudbuild.yaml
--- a/webui/cypress/cloudbuild.yaml
+++ b/webui/cypress/cloudbuild.yaml
@@ -33,6 +33,31 @@ steps:
   - name: cypress/base
     waitFor: ['Prepare', 'Generate Client', 'Generate User Service Client']
     id: Test
-    entrypoint: npm
-    args: ['run', 'e2e', '--', '--config', 'baseUrl=https://${_DOMAIN}']
+    entrypoint: /bin/bash
+    args:
+    - -c
+    - |
+      npm run e2e -- --config baseUrl=https://${_DOMAIN} || { touch ../e2e-failed && npm run cleanup; }
     dir: 'webui'
+  - name: 'google/cloud-sdk:latest'
+    waitFor: ['Test']
+    id: Upload artifacts
+    entrypoint: /bin/bash
+    args:
+    - -c
+    - |
+      gsutil -m cp -r videos/* gs://${_ARTIFACTS_LOCATION}/${BUILD_ID} || true
+      gsutil -m cp -r screenshots/* gs://${_ARTIFACTS_LOCATION}/${BUILD_ID} || true
+    dir: 'webui/cypress'
+  - name: 'alpine'
+    id: Set build status
+    waitFor: ["Upload artifacts"]
+    entrypoint: /bin/ash
+    args:
+    - -c
+    - |
+      if [ -e e2e-failed ]
+      then
+        echo "Tests failed!"
+        exit 1
+      fi
